export const GAMES = [
  {
    id: 'candy_match',
    name: 'Candy Match',
    emoji: '🍬',
    description: 'Find matching candy pairs!',
    difficulty: 'Easy',
    ageRange: '3-8',
    colors: ['#FF6B6B', '#4ECDC4'],
    levels: 100,
    icon: '🎴',
  },
  {
    id: 'candy_catch',
    name: 'Candy Catch',
    emoji: '🍭',
    description: 'Catch falling candies in your basket!',
    difficulty: 'Easy',
    ageRange: '3-6',
    colors: ['#FF69B4', '#9B59B6'],
    levels: 50,
    icon: '🧺',
  },
  {
    id: 'candy_sort',
    name: 'Candy Sort',
    emoji: '🍫',
    description: 'Sort candies by color and shape!',
    difficulty: 'Easy',
    ageRange: '2-5',
    colors: ['#F1C40F', '#E67E22'],
    levels: 40,
    icon: '🗂️',
  },
  {
    id: 'candy_memory',
    name: 'Candy Memory',
    emoji: '🧠',
    description: 'Remember the candy sequence!',
    difficulty: 'Medium',
    ageRange: '4-8',
    colors: ['#9B59B6', '#E67E22'],
    levels: 80,
    icon: '🎯',
  },
  {
    id: 'candy_pop',
    name: 'Candy Pop',
    emoji: '🎈',
    description: 'Pop floating candy balloons!',
    difficulty: 'Medium',
    ageRange: '3-7',
    colors: ['#E74C3C', '#FF6B6B'],
    levels: 60,
    icon: '🎈',
  },
  {
    id: 'candy_count',
    name: 'Candy Count',
    emoji: '🔢',
    description: 'Learn numbers by counting candies!',
    difficulty: 'Easy',
    ageRange: '2-5',
    colors: ['#3498DB', '#2ECC71'],
    levels: 30,
    icon: '1️⃣',
  },
  {
    id: 'candy_color',
    name: 'Candy Color',
    emoji: '🎨',
    description: 'Match candy to color name!',
    difficulty: 'Easy',
    ageRange: '2-4',
    colors: ['#2ECC71', '#3498DB'],
    levels: 20,
    icon: '🎨',
  },
  {
    id: 'candy_puzzle',
    name: 'Candy Puzzle',
    emoji: '🧩',
    description: 'Complete the candy picture!',
    difficulty: 'Medium',
    ageRange: '4-8',
    colors: ['#2ECC71', '#3498DB'],
    levels: 50,
    icon: '🧩',
  },
  {
    id: 'candy_rush',
    name: 'Candy Rush',
    emoji: '⚡',
    description: 'Tap matching candies quickly!',
    difficulty: 'Hard',
    ageRange: '5-8',
    colors: ['#F1C40F', '#E67E22'],
    levels: 70,
    icon: '⚡',
  },
  {
    id: 'candy_bingo',
    name: 'Candy Bingo',
    emoji: '🎲',
    description: 'Match candies on bingo card!',
    difficulty: 'Medium',
    ageRange: '4-8',
    colors: ['#9B59B6', '#E74C3C'],
    levels: 40,
    icon: '🎲',
  },
];

export const getGameById = (id) => GAMES.find(game => game.id === id);